### ISSUE TITLE
returning true from eof_received() has no effect when using ssl

### ISSUE THREAD

**Issue by ra0mb1er** [constverum/ProxyBroker#5]
returning true from eof_received() has no effect when using ssl,    why  returun this?  plz help me, thx :)

**Comment by constverum** [comment]
Yes, I know about the [warning message](https://github.com/python/asyncio/blob/master/asyncio/sslproto.py#L527) (when logging is active). But to work it actually has no effect.

This warning message occurs because a half-closed connection, which is not supported SSL, see [Protocol.eof_received()](https://docs.python.org/dev/library/asyncio-protocol.html#asyncio.Protocol.eof_received).

It occurs after we establish a secure connection to the proxy judge, and when the page is requested. For some reason some proxies at this point, terminate the connection by sending EOF (when you enabled logging, you can see that often it is the same proxy).

In code:
```python
# proxy.py#L193
resp = await asyncio.wait_for(
self._reader.read(length), timeout=self._timeout)
```

If we do check for EOF prior to this string of (`self._reader.at_eof()`), we see that EOF is False. But after this string EOF is True and the warning is already added. So I don't see any possibility to intercept the warning about receiving EOF when SSL is active =(
