### ISSUE TITLE
how can i get all proxys without check

### ISSUE THREAD

**Issue by ra0mb1er** [constverum/ProxyBroker#6]
import asyncio
from proxybroker import Broker
outFile=open('result.txt','w')
loop = asyncio.get_event_loop()

proxies = asyncio.Queue(loop=loop)
broker = Broker(proxies, loop=loop)
loop.run_until_complete(broker.grab(limit=1000))
while True:
    proxy = proxies.get_nowait()
    if proxy is None: break
    print('Found proxy: %s' % proxy)
    outFile.write(str(proxy)+'\n')

hi i this is my code ,when limit over 10K ,it is error ,how can i get all proxys without check

**Comment by constverum** [comment]
What kind of error occurs?

I can assume that the impression that at the end of parsing, nothing happens and the program hangs? This is not so. 

The fact is that at the end of the parsing is working with proxy brokers who have thousands of proxies specified in the format domain and not ip. And so as not to duplicate proxy in the results we must do resolve these domains to get their ip.

Resolving the several thousand of domains takes time, so a _two minutes_ it may seem that nothing is happening. Usually by this time the number of collected proxies should be about ~30k. And ~40k at the end.

If I have assumed incorrectly, please use logging and post the result (with traceback):
```python
# insert at the beginning of executable file
import logging
logging.basicConfig(
    filename='./issue6.log',
    format='%(asctime)s - %(levelname)s - %(name)s - %(message)s',
    datefmt='[%H:%M:%S]',
    level=logging.DEBUG)
```

**Comment by ra0mb1er** [comment]
have no response from proxy website  , have many error ,for example  Error: ClientResponseError()

http://www.proxynova.com/proxy-server-list/country-ee/ is failed. Error: ClientResponseError();
http://www.proxynova.com/proxy-server-list/country-ch/ is failed. Error: ClientResponseError();
http://www.get-proxy.net/proxy-archives is failed. Error: ClientOSError(111, "Cannot connect to host www.get-proxy.net:80 ssl:False [Can not connect to www.get-proxy.net:80 [Connect call failed ('46.36.220.67', 80)]]");
http://www.get-proxy.net/proxy-archives is failed. Error: ClientOSError(111, "Cannot connect to host www.get-proxy.net:80 ssl:False [Can not connect to www.get-proxy.net:80 [Connect call failed ('46.36.220.67', 80)]]");
http://www.get-proxy.net/proxy-archives is failed. Error: ClientOSError(111, "Cannot connect to host www.get-proxy.net:80 ssl:False [Can not connect to www.get-proxy.net:80 [Connect call failed ('46.36.220.67', 80)]]");
http://free-proxy.cz/en/proxylist/main/date/14 is failed. Error: BadStatusError('Status: 403',);
http://free-proxy.cz/en/proxylist/main/date/1 is failed. Error: BadStatusError('Status: 403',);
http://free-proxy.cz/en/proxylist/main/date/6 is failed. Error: BadStatusError('Status: 403',);
http://free-proxy.cz/en/proxylist/main/date/5 is failed. Error: BadStatusError('Status: 403',);
http://free-proxy.cz/en/proxylist/main/date/14 is failed. Error: BadStatusError('Status: 403',);
http://free-proxy.cz/en/proxylist/main/date/5 is failed. Error: BadStatusError('Status: 403',);
http://free-proxy.cz/en/proxylist/main/date/1 is failed. Error: BadStatusError('Status: 403',);
http://free-proxy.cz/en/proxylist/main/date/6 is failed. Error: BadStatusError('Status: 403',);
http://free-proxy.cz/en/proxylist/main/date/14 is failed. Error: BadStatusError('Status: 403',);
http://free-proxy.cz/en/proxylist/main/date/5 is failed. Error: BadStatusError('Status: 403',);
http://free-proxy.cz/en/proxylist/main/date/6 is failed. Error: BadStatusError('Status: 403',);
http://free-proxy.cz/en/proxylist/main/date/1 is failed. Error: BadStatusError('Status: 403',);

**Comment by constverum** [comment]
There are two causes of errors:

1. Sites try to protect themselves from parsing. 
And they do it in different ways, some of them proxybroker can pass, and some may not. In the case of proxynova.com errors arise from a large number of requests. Alternatively, you can try to put a wait between the requests, but I think it's not effective. 
With free-proxy.cz is a similar story, but in their case, the defense bypass will not work at all. Even by default, we grab only the first 15 pages, because it was followed the block on your IP for a day or longer. They use reCAPTCHA =) Last time and did not get to even get to 15 pages, probably there was extra protection and have to remove them from the list of providers.

2. The websites at the moment are simply not working. For example try to open in browser get-proxy.net. 

These problems are unsolvable. That's why the sites that are likely to have problems at the end of the collection proxy. Therefore, the main part of the tens of thousands of proxies and 90% of the sources (what is already quite a lot) you will receive without problems, and remaining (free-proxy.cz & get-proxy.net) only partially if you're lucky =)
